# This is a basic workflow to help you get started with GitHub CI using ActivePython
name: ActivePython application on GitHub CI

# Setting up Cache directory and ActiveState Platform API key
env:
  ACTIVESTATE_CLI_CACHEDIR: ${{ github.workspace }}/.cache        
  ACTIVESTATE_API_KEY: ${{ secrets.ACTIVESTATE_API_KEY }}  
  
# Controls when the action will run. Triggers the workflow on push events on the default branch 
on: [push]

# A CI workflow  is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on (this one is a matrix build)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Building on both Windows, Linux(Ubuntu) and Mac simultaneously 
        os: [macos-latest]       
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: set deployment dir
      run: echo "::add-path::/deployment/bin"
    - name: make deployment dir
      run: mkdir -p /deployment/bin
      shell: bash
    # Installing State Tool on Windows via Powershell 
    - name: Install State Tool (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        (New-Object Net.WebClient).DownloadFile('https://platform.activestate.com/dl/cli/install.ps1', 'install.ps1'); 
        Invoke-Expression -Command "$Env:GITHUB_WORKSPACE\install.ps1 -n -t $Env:GITHUB_WORKSPACE"
        echo "::add-path::$Env:GITHUB_WORKSPACE"
      shell: powershell
    # Installing State Tool on Linux with default shell behavior
    - name: Install State Tool (Linux)            
      if: matrix.os != 'windows-latest'      
      run: sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) -n
    # Checking ActiveState Platform for project updates
    #- name: Update project
    #  run: state pull
    # Checking ActiveState Platform for project updates
    - name: Deploy project
      if: matrix.os != 'windows-latest'      
      run: state deploy MyOrg/learn-python --path /deployment/bin
    - name: Deploy project (Windows)
      if: matrix.os == 'windows-latest'
      run: state deploy MyOrg/learn-python
      shell: cmd
    # Caching downloaded build using GitHub CI cache
    - name: Cache state tool cache
      uses: actions/cache@v1
      env:
        cache-name: cache-platform-build
      with:
        path: ${{ env.ACTIVESTATE_CLI_CACHEDIR }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('activestate.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
    # Execute linting of the project on ActivePython
    - name: Lint with pylint
      run: |
        echo $PATH
        export PATH=/Users/runner/runners/2.169.1/work/learn-python/learn-python/.cache/bin:$PATH
        echo $PATH
        ls /Users/runner/runners/2.169.1/work/learn-python/learn-python/.cache/bin
        pylint src
      shell: bash
    - name: Lint with flake8
      run: flake8 src --statistics --count
    # Running project tests using pytest on ActivePython
    - name: Test with pytest
      run: pytest
